<?php
/**
 * IDEALIAGroup srl
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@idealiagroup.com so we can send you a copy immediately.
 *
 * @copyright  Copyright (c) 2017 IDEALIAGroup srl (http://www.idealiagroup.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var $this MSP_Qapla_Block_Adminhtml_System_Config_Button */
?>

<script type="text/javascript">
    function checkApi() {
        var key = document.getElementById("msp_qapla_general_api_key").value;

        if(key.trim() == "") {
            alert("Insert API Key.");
            return;
        }
        new Ajax.Request('<?php echo $this->_getCheckUrl() ?>?apikey=' + key,  {
            method:     'get',
            onSuccess: function(transport){

            if (transport.responseText){
                var data = JSON.parse(transport.responseText);
                var message = "";

                if(data.error) {
                    message = "Something was wrong: " + data.message;
                }
                else {
                    if(data.message) {
                        message = "Your key is valid";
                    }
                    else {
                        message = "Invalid key";
                    }
                }

                alert(message);
            }
        }
        });
    }
</script>

<?php echo $this->_getButtonHtml() ?>